name: Node.js Package

on: [push]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    name: Publish to NPM
    env:
      FORCE_COLOR: 1
    steps:
      - uses: actions/checkout@v2
        name: Checkout Repository
      - uses: actions/setup-node@v1
        name: Setup Node
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}

  publish-github-packages:
    runs-on: ubuntu-latest
    name: Publish to GitHub Packages
    env:
      FORCE_COLOR: 1
    steps:
      - uses: actions/checkout@v2
        name: Checkout Repository
      - uses: actions/setup-node@v1
        name: Setup Node
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
        name: Install Packages
      - run: |
          mv package.json package.json.npm
          jq -r '.name |= "@ethomson/card"' package.json.npm > package.json
          rm package.json.npm
      - run: npm publish
        name: Publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
